name: 'Build Plugin'

on:
  pull_request:
    branches:
      - master
      - 10.7.x-compat
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/build.yaml@master
